# See https://pre-commit.com/ for usage and config
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

#  - repo: local
#    hooks:
#    #   - id: black
#    #     name: black
#    #     stages: [commit]
#    #     language: system
#    #     entry: black
#    #     types: [python]
#    #     files: .*\.py$
#
#      - id: flake8
#        name: flake8
#        stages: [commit]
#        language: system
#        entry: flake8
#        types: [python]
