#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi
if [ -d 'faust.egg-info' ] ; then
    rm -r faust.egg-info
fi

rm -rf .coverage.*
rm -rf *.logs
