#!/bin/sh -e

VERSION_FILE="faust/__init__.py"

if [ -d 'venv' ] ; then
    PREFIX="venv/bin/"
else
    PREFIX=""
fi

VERSION=`grep __version__ ${VERSION_FILE} | grep -o '[0-9][^"]*'`

set -x

${PREFIX}twine upload dist/*
# ${PREFIX}mkdocs gh-deploy --force

git tag -a v${VERSION} -m "release v${VERSION}"
git push origin v${VERSION}
