name: Pages
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
on:
  push:
    branches:
    - master
    - gh-pages-test
jobs:
  generate-docs:
    name: "Update GitHub Pages"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: "Build docs"
      uses: sphinx-notes/pages@v2
      with:
        requirements_path: ./requirements/docs.txt
        sphinx_version: 5.1.1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'gh-pages-test-deploy'
