name: Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [created]
    branches:
      - 'master'

jobs:
  build:
    name: "Build docs"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: "Install runtime dependencies"
      run: "scripts/install"
    - name: "Install doc build deps and build with Sphinx"
      run: make docs
    - name: "Upload artifacts"
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload built docs
        path: "./Documentation"
  deploy:
    name: "Deploy docs"
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: build
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v2
      id: deployment
      name: "Deploy to GitHub Pages"
